const char* html_page_template = 
"<!DOCTYPE html>"
"<html lang=\"en\">"
"<head>"
"<meta charset=\"UTF-8\">"
"<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">"
"<title>Pico2 Dashboard</title>"

"<style>"
"body { margin: 0; font-family: 'Segoe UI', sans-serif; background: linear-gradient(135deg, #0d1117, #161b22); color: #c9d1d9; display: flex; justify-content: center; align-items: center; min-height: 100vh; padding: 20px; box-sizing: border-box; }"
".container { width: 100%%; max-width: 900px; }"
".header { text-align: center; margin-bottom: 25px; }"
".header h1 { color: #58a6ff; margin-bottom: 5px; font-size: 1.8rem; }"
".header p { margin: 0; color: #8b949e; }"
".grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); gap: 15px; }"
".card { background: #161b22; padding: 18px; border-radius: 12px; box-shadow: 0 4px 15px rgba(0,0,0,0.4); border-left: 4px solid #30363d; }"
".card h2 { margin: 0 0 10px 0; font-size: 0.95rem; color: #8b949e; text-transform: uppercase; letter-spacing: 0.5px; }"
".value { font-size: clamp(1.1rem, 4vw, 1.3rem); font-weight: 600; line-height: 1.35; }"
".footer { text-align: center; margin-top: 30px; font-size: 0.8rem; color: #6e7681; }"
"</style>"
"</head>"

"<script>"
"setInterval(async () => {"
"  try {"
"    const resp = await fetch(window.location.href);"
"    const text = await resp.text();"
"    const parser = new DOMParser();"
"    const doc = parser.parseFromString(text, 'text/html');"
"    const newVals = doc.querySelectorAll('.value');"
"    const curVals = document.querySelectorAll('.value');"
"    newVals.forEach((el, i) => {"
"      if (curVals[i]) curVals[i].innerHTML = el.innerHTML;"
"    });"
"    const newFoot = doc.querySelector('.footer');"
"    if (newFoot) document.querySelector('.footer').innerHTML = newFoot.innerHTML;"
"  } catch(e) {}"
"}, 10000);"
"</script>"

"<body>"
"<div class=\"container\">"
"  <div class=\"header\">"
"    <h1>W6100-EVB-Pico2</h1>"
"    <p>Secure Sensor Dashboard</p>"
"  </div>"
"  <div class=\"grid\">"
"    <div class=\"card\">"
"      <h2>System Time</h2>"
"      <div class=\"value\">%04d-%02d-%02d <br> %02d:%02d:%02d</div>"
"    </div>"
"    <div class=\"card\">"
"      <h2>Uptime & Peak</h2>"
"      <div class=\"value\">%s | %u act</div>" // Changed %u s to %s
"    </div>"
"    <div class=\"card\">"
"      <h2>Temperature</h2>"
"      <div class=\"value\">%.2f &deg;C</div>"
"    </div>"
"    <div class=\"card\">"
"      <h2>CO2 Level</h2>"
"      <div class=\"value\">%d ppm</div>"
"    </div>"
"    <div class=\"card\">"
"      <h2>PM 1.0</h2>"
"      <div class=\"value\">%.1f &micro;g/m&sup3;</div>"
"    </div>"
"    <div class=\"card\">"
"      <h2>PM 2.5</h2>"
"      <div class=\"value\">%.1f &micro;g/m&sup3;</div>"
"    </div>"
"  </div>"
"  <div class=\"footer\">IP: %s | mbedTLS secured | Auto-refresh 10s</div>"
"</div>"
"</body>"
"</html>";

